# Generated by Django 6.0.6 on 2026-06-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('professional_summary', models.TextField(verbose_name='Professional Summary')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('technical_skills', models.JSONField(blank=True, default=dict, verbose_name='Technical Skills')),
                ('education', models.JSONField(blank=True, default=list, verbose_name='Education')),
                ('certifications', models.JSONField(blank=True, default=list, verbose_name='Certifications')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies_used', models.CharField(max_length=500, verbose_name='Technologies Used (comma separated)')),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, help_text='e.g. 3 Months, Jan 2021 - Apr 2021', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_and_responsibilities', models.TextField(help_text='Enter roles/responsibilities, one per line (each will become a bullet point)', verbose_name='Role & Responsibilities')),
                ('duration', models.CharField(blank=True, help_text='Override project duration if different for this employee', max_length=100, null=True)),
                ('client', models.CharField(blank=True, help_text='Override project client if different for this employee', max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the resume (lower values first)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_mappings', to='resumes.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='resumes.project')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('employee', 'project')},
            },
        ),
    ]
